# Generated by Django 2.2.7 on 2019-11-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restourant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restourant_name', models.CharField(max_length=200)),
                ('restourant_adress', models.CharField(max_length=200)),
            ],
        ),
    ]
