# Generated by Django 2.2.7 on 2019-11-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
