# Generated by Django 2.2.6 on 2019-11-24 08:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_restaurant_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('price', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('img', models.ImageField(default='NULL', upload_to='img/')),
                ('rest', models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant')),
                ('time', models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='main.Time')),
            ],
        ),
    ]
