# Generated by Django 2.2.6 on 2019-11-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
