# Generated by Django 2.2.6 on 2019-11-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
