# Generated by Django 2.2.6 on 2019-12-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='rest',
        ),
        migrations.RemoveField(
            model_name='food',
            name='time',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
