# Generated by Django 2.2.6 on 2019-12-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20191208_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='time',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='P', max_length=2),
            preserve_default=False,
        ),
    ]
