# Generated by Django 2.2.6 on 2019-12-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_food_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.CharField(blank=True, choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], max_length=2, null=True),
        ),
    ]
