# Generated by Django 2.2.6 on 2019-12-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
