# Generated by Django 2.2.7 on 2019-12-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20191209_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ordered_date',
            field=models.DateTimeField(),
        ),
    ]
